### ISSUE TITLE
Changes needed for Account Search API

### ISSUE THREAD

**Issue by LucyYYW** [pennlabs/platform#69]
Hi, here are some changes we want for the Account Search API:
1. We want some other fields additional to "first_name", "last_name" and "pennkey":

- email

- pennid

2. We want to enable search by "last_name" and "pennkey", since right now it is only allowing searching by "first_name".
3. We also want the results to be sorted (in any appropriate way).

**Comment by ArmaanT** [comment]
What's the plan for how this endpoint is going to be used? Which of our products is going to make the api request and what info will be shown to the user?

**Comment by joshdoman** [comment]
I don't think we will show email anymore. I thought Wharton did, and it was part of the original Group GSR invite design, but I was wrong. 

PennID's will not be shown to the user. Right now, the Group GSR invite endpoint identifies the invitee via pennkey. I was under the impression that we wanted to move everything internally that deals with identifying users to pennid. If that's not the case, then a pennid field is not necessary. 

There is a legitimate security concern if we add a pennid field because a malicious user could use their personal access token to get everyone's pennid by trying possible search query.

**Comment by ArmaanT** [comment]
Closed by #70
